### PR TITLE
docs: add spaceduck.lua to themes

### PR DESCRIPTION
**Pull request by pineapplegiant**
Hey this is my first official pull request, so hopefully I did everything right.

I made the [ vim spaceduck colorscheme](https://github.com/pineapplegiant/spaceduck), and I really like your plugin so hopefully this works so others can use it. I ran the `lua-format` using your config, like you suggested, and just copied gruvbox's theme as a starter template to making the theme. Let me know if I should make any changes.

Cheers 🍻

### CODE REVIEW

**Comment by shadmansaleh** [comment]
You know you can put lualine themes in your repo too just like airline and lightline themes . You will have to put it in lua/lualine/themes directory in your repo. That way any user installing your colorscheme can use your lualine theme even if it's not in lualine repo :)

**Comment by pineapplegiant** [comment]
That probably makes more sense to do it that way @shadmansaleh

**Comment by pineapplegiant** [comment]
Should I close the pull request then? 😆

**Comment by shadmansaleh** [comment]
I think you should keep it open until @hoob3rt says something about whether he will include it in the repo or not :)

**Comment by hoob3rt** [comment]
Hi! Thaks for your contribution. I actually stumbled across spaceduck a while ago and think it's a really nice theme so I'm all for having it merged. I will take a look at the code in a few hours from now :smile:

**Comment by pineapplegiant** [comment]
@hoob3rt, that makes the most sense to me as well! Thanks again for creating this wonderful plugin 🚀

**Pull request closed without merging**
