### PR TITLE
Add tabline support

### PR DESCRIPTION
**Pull request by shadmansaleh**
Now components can optionaly be placed on tabline too.

This is what I was talking about in #89
in configs I can set:
```lua
lualine.tabline.lualine_b = {'branch'}
```
And branch component will apear on top of window in tabline .

>There are already existing lua implementations of tabline so I don't think it is necessary for us to implement it

I donn't think anyone else is providing this.

@hoob3rt what do you think 10LOC is it worth adding the option ?

### CODE REVIEW

**Comment by shadmansaleh** [comment]
@hoob3rt you still haven't tolded me your opinion on this

**Comment by hoob3rt** [comment]
> @hoob3rt you still haven't tolded me your opinion on this

I'm not a big fan of this idea but this is a topic for another day. We should focus on other, more important pr's first

**Comment by shadmansaleh** [comment]
Alright. It's completely optional so unless someone explictly sets it it wonn't have any affect at all. I agree other prs need more attention.

**Comment by hoob3rt** [comment]
Okay I can agree on having this as some users might want to have dual statusline or statusline on top. This needs to have both `README.md` and `docs` updated

**Comment by shadmansaleh** [comment]
@hoob3rt conflicts resolved . If you're fine with the changes merge this :)

**Comment by hoob3rt** [comment]
I am. I'm just thinking we should also have a screenshot of the tabling enabled. I will think on how to integrate it nicely into the readme. If you have any config you want to show off the paste it here

**Comment by shadmansaleh** [comment]
I donn't really have specific config you can put screenshots for the config example in the README.md

**Comment by hoob3rt** [comment]
Okay, I will try doing it today

**Comment by wcpines** [comment]
I wanted to test this out and tried installing it as a branch with vim-plug. Getting `fatal: invalid reference: shadmansaleh:add_tabline_support`.  

Any suggestions?

**Comment by hoob3rt** [comment]
> I wanted to test this out and tried installing it as a branch with vim-plug. Getting `fatal: invalid reference: shadmansaleh:add_tabline_support`.
> 
> Any suggestions?

I don't think you can install fork branch with vim plug. Sorry it's taking so long, I've got some job related stuff to do. I will merge and integrate this into readme tomorrow.

**Comment by shadmansaleh** [comment]
> I wanted to test this out and tried installing it as a branch with vim-plug. Getting fatal: invalid reference: shadmansaleh:add_tabline_support.

Any suggestions?

switch to.
```vim
Plug 'shadmansaleh/lualine.nvim', { 'branch': 'add_tabline_support' }
```
once you're done switch back to
```vim
Plug 'hoob3rt/lualine.nvim'
```

**Comment by wcpines** [comment]
This is almost certainly out of scope for this PR, but would it be possible to make the tabline behavior respect multiple tabs, [similar to airline](https://github.com/vim-airline/vim-airline#smarter-tab-line)? (Happy to create a separate issue if desired)

**Comment by shadmansaleh** [comment]
> This is almost certainly out of scope for this PR, but would it be possible to make the tabline behavior respect multiple tabs, similar to airline? 

We have decided it's out of scope of this plugin . There are lua plugins that directly handly the kind of tabline ypu're looking for . You can tryout [nvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua) or [barbar.nvim](https://github.com/romgrk/barbar.nvim) .

**Pull request merged**
