### PR TITLE
Added Powerline like > < separators

### PR DESCRIPTION
**Pull request by shadmansaleh**
solution for #21

It works, doesn't look bad .
Need to do some cleanup on the code.

Demo

### CODE REVIEW

**Comment by shadmansaleh** [comment]
I think it's quite stable now

**Comment by shadmansaleh** [comment]
Does anyone know of any unicode symbles that can be used for this without patched fonts?

**Comment by hoob3rt** [comment]
I think we should keep separators from https://github.com/hoob3rt/lualine.nvim/pull/55/commits/ef3dff46b492b2d5198f2c81159416433e7fe8e7 as default. They work with nerd fonts well while the current defaults crash on nerd fonts and display funny emojis with emoji theme installed

pic-window-210110-0036-00

**Comment by hoob3rt** [comment]
> pic-window-210110-0036-00

Also there is a new visible bug, there should be no separator after `filaneme` or before `utf-8` here.

**Comment by shadmansaleh** [comment]
>I think we should keep separators from ef3dff4 as default. They work with nerd fonts well while the current defaults crash on nerd fonts and display funny emojis with emoji theme installed

Funny naver thought they would look like this . Though it will be a small fix.

**Comment by shadmansaleh** [comment]
> Also there is a new visible bug, there should be no separator after filaneme or before utf-8 here.

Why not ?

**Comment by shadmansaleh** [comment]
changed to nerd font separators

**Comment by shadmansaleh** [comment]
>Also there is a new visible bug, there should be no separator after filaneme or before utf-8 here.

I've realized they aren't found in powerline . I've removed them

**Comment by shadmansaleh** [comment]
Closed in favor of #94.

**Pull request closed without merging**
