### PR TITLE
feat(filename): add support for custom filename symbols (modified, readonly)

### PR DESCRIPTION
**Pull request by timbedard**
Let's let users customize these symbols as well. Color would be nice too, eventually.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
The implementation looks right . But a few things need to change before it can be merged.

1. You need to document the option in README.md and doc/lualine.txt
2. Changes from #184 needs to go . Those have been merged already :P 
3. I don't know why you've changed the single quotes to double quotes . In the repo singles are used . Run lua-format from base of repo . That should fix it . I'm assuming you ran it from some other dir thus config didn't get applied

**Comment by timbedard** [comment]
Ha ha. Too fast for you.

And the quotes were because of lua-fmt, which doesn't have a single quote option. 🙄 Guess I need to actually get lua-format working.

Should be good to go.

**Review by shadmansaleh — APPROVED** [review]

**Comment by shadmansaleh** [comment]
> Should be good to go

Indeed in my opinion . But I can't merge it . When @hoob3rt comes along he'll do it :]

**Review by hoob3rt — APPROVED** [review]
lgtm, we can merge this one, thank you both :smile:

**Pull request merged**
