### PR TITLE
Add gruvbox light theme

### LINKED ISSUE #188: Feat: Add gruvbox light variant
We have light and dark versions of Solarized, so perhaps it's a good idea to add the light version for Gruvbox?

### PR DESCRIPTION
**Pull request by minhduc0711**
Adapted from the gruvbox light theme in vim-airline.
Close #188

### CODE REVIEW

**Comment by hoob3rt** [comment]
theme looks good, but screenshots need updating after c7d0fd8

**Comment by minhduc0711** [comment]
Oh the colors did not change, I stylized `xyz` as `cba` without noticing it was the default behavior if `xyz` are omitted.

**Comment by hoob3rt** [comment]
oh yeah, my bad, take ss with this config then
```lua
require'lualine'.setup {
  options = {
    theme = 'gruvbox_light',
    component_separators = '|',
    section_separators = ''
  }
}

```

**Comment by minhduc0711** [comment]
Screenshots updated!

**Comment by hoob3rt** [comment]
lgtm, thanks

**Pull request merged**
