### PR TITLE
Add component evaluation for inactive sections

### LINKED ISSUE #157: Bug: File modification indicator ([+]) not updated for inactive windows
Thanks for the great project 👍

Btw, it looks that the indicator for file modification, [+], doesn't get updated for inactive windows.
The following gifs show some demonstrations.

filemodified

diffedit

### PR DESCRIPTION
**Pull request by shadmansaleh**
Now filename component updates on inactive_status .

closes #157

### CODE REVIEW

**Comment by hoob3rt** [comment]
this reproduces #208 at least for my machine.

Also I think we should discuss which components should update in inactive state. I would go for
* filetype (already done here)
* diagnostics 
* progress
* location (not sure about this one)

My reasoning behind this is all of above are cheap to run performance wise and could change while doing a sed-like edit as mentioned in #157.

**Comment by shadmansaleh** [comment]
> this reproduces #208 at least for my machine.

Of cource I branched off before the patch . A rebase on master will fix it on this branch.

There's an issue with this `%{}` evaluation escapes `%` in results and I've no idea how to tackle that . It won't be a problem for components that don't emmit % codes but the ones that do causes issues . I'm not sure how progress or location may change in an inactive buffer . They seem like a prime candidate for static component .

**Comment by hoob3rt** [comment]
> I'm not sure how `progress` or `location` may change in an inactive buffer . They seem like prime candidates for static component .

Yeah, my bad. I double checked and my idea was wrong, nevermind that. 



> There's an issue with `%{}` evaluation escapes `%` in results and I've no idea how to tackle that . It won't be a problem for components that don't emmit % codes but the ones that do causes issues .

Could you elaborate? I don't understand the issue atm.

**Comment by shadmansaleh** [comment]
> Could you elaborate? I don't understand the issue atm.

Means %3P from progress displays as %3P as (neo)vim either doesn't evaluate the result or escapes the % in %3P

**Comment by hoob3rt** [comment]
> > Could you elaborate? I don't understand the issue atm.
> 
> Means %3P from progress displays as %3P as (neo)vim either doesn't evaluate the result or escapes the % in %3P

We can easily move to our custom statusline functions instead of using the builtins, that should resolve our problem right?

`location` can be handled easily by `vim.api.nvim_win_get_cursor`, although location would require us to reimplement `%3P` logic ourselves from scrach unless there is another `vim.api` function to handle it

**Comment by shadmansaleh** [comment]
> We can easily move to our custom statusline functions instead of using the builtins, that should resolve our problem right?

Those components aren't the real issue the highlights are . They are applied like `%#hl_name#` . The themes and color option work as they get applied outside of `%{}` evaluation . But components that have their own highlight group and handle them internaly doesn't (diagnostics for example).  Maybe we can provide diagnostics without highlights just with symbols for inactive_status.

**Comment by shadmansaleh** [comment]
@hoob3rt any idea why checks aren't running here ?

**Comment by hoob3rt** [comment]
> Maybe we can provide diagnostics without highlights just with symbols for inactive_status.

I don't like this tbh.

Honestly I don't know what to do with this issue... We should find a working solution for this otherwise it could cause problems down the line

**Comment by shadmansaleh** [comment]
> I don't like this tbh.

I don't like it much either. But I've no idea how to solve it :D

**Pull request closed without merging**
