### PR TITLE
docs: updated luline.txt

### PR DESCRIPTION
**Pull request by hoob3rt**
removes bloat from docs
- [x] cleanup lualine.txt
- [x] fix spelling in lualine.txt
- [x] cleanup README.md
- [x] fix spelling in README.md
- [x] update tags

### CODE REVIEW

**Comment by hoob3rt** [comment]
@shadmansaleh how exactly are tags supposed to work when we have no `docs/tags` in the repo? I forgot how #187 is a relevant fix

**Comment by shadmansaleh** [comment]
I think package managers creates and updates the tags . While you're at it change tags from `lualine_a_b` to `lualine-a_b` . the `-` isolates the tag to the file . Also can I get some reviews on my prs :D

**Comment by hoob3rt** [comment]
> Package managers creates and updates the tags .For example [packer](https://github.com/wbthomason/packer.nvim/blob/c51be59d62ac0b4fca80a4a4d75ab0870f494246/lua/packer/plugin_utils.lua#L85), [vimPlug](https://github.com/junegunn/vim-plug/blob/fc2813ef4484c7a5c080021ceaa6d1f70390d920/plug.vim#L798). While you're at it change tags from `lualine_a_b` to `lualine-a_b` . the `-` isolates the tag to the file . 

So `lualine_theme` to `lualine-theme` and `lualine_config_examples` to `lualine-config_examples`?

**Comment by shadmansaleh** [comment]
> So lualine_theme to lualine-theme and lualine_config_examples to lualine-config_examples

yes

**Comment by hoob3rt** [comment]
@shadmansaleh this is done, honestly I'm extremely happy with how this turned out. It's a lot cleaner imo. I also removed most of the folds like you wanted some time ago :smile:

**Pull request merged**
