### PR TITLE
Refactor: Classify components

### PR DESCRIPTION
**Pull request by shadmansaleh**
The idea is to create components in somewhat oop style . The component.lua file added willa ct as a base class and components will extend it by mainly implementing update_status() function.

@hoob3rt should I go forward whith this ?

### Todo
- [x] Add component base class
- [x] Migrate components to this structure
- [x] Update init.lua + section.lua to use this system
- [x] Change special and functiom components to this format .
- [x] Remove all the unesseary stuff from utils and init.lua
- [x] Testing (I think I'm satisfied with the testing. You can report bugs if you find any)

### CODE REVIEW

**Comment by hoob3rt** [comment]
Yes that's great. I once tried to do it this way but stumbled across some issues. I will gladly move to this though since it will make the code cleaner imo

**Comment by hoob3rt** [comment]
It looks like this is ready for hand testing and review? 

This will also make #127 a lot easier if we move with it so I appreciate this a lot

**Comment by shadmansaleh** [comment]
> It looks like this is ready for hand testing and review?

Testing and reporting bugs will be definatly apreciated . 
If you have time you can do a review .  Most of the stuff won't change . Though don't merge as long as I have WIP in title.

**Comment by shadmansaleh** [comment]
> I once tried to do it this way but stumbled across some issue

What issues did you face ?

**Comment by hoob3rt** [comment]
> > I once tried to do it this way but stumbled across some issue
> 
> What issues did you face ?

Don't remember right now. 

Also bug report:
component separators are not displaying for me

**Comment by shadmansaleh** [comment]
> component separators are not displaying for me

 Are you on the latest commit ? I had fixed it yesterday and after that it is working for me .

**Comment by shadmansaleh** [comment]
I think I'm done. You can do a review. If you don't have problems you can merge :)

**Comment by hoob3rt** [comment]
> > component separators are not displaying for me
> 
> Are you on the latest commit ? I had fixed it yesterday and after that it is working for me .

I am, the separators are now. displaying but there is another bug I noticed. It's hard to explain so I will post a video later

**Comment by shadmansaleh** [comment]
> It's hard to explain

Short description?

**Comment by hoob3rt** [comment]
> > It's hard to explain
> 
> Short description?

Actually good thing you pushed me to try and document this. It was a mistake on my part, I noticed something that wasn't there lol. Separators seem to be working fine. 🎉

**Comment by hoob3rt** [comment]
> I think I'm done. You can do a review. If you don't have problems you can merge :)

Okay, you can expect a review on Saturday, if I somehow have time then I will do it tomorrow.

**Comment by shadmansaleh** [comment]
> Actually good thing you pushed me to try and document this. It was a mistake on my part, I noticed something that wasn't there lol.

😁 will you have time to review this today ?

**Comment by hoob3rt** [comment]
> > Actually good thing you pushed me to try and document this. It was a mistake on my part, I noticed something that wasn't there lol.
> 
> 😁 will you have time to review this today ?

As I've told you I'm low on time this week, a lot of stuff going on. See above comment for review estimation

**Comment by hoob3rt** [comment]
I'm feeling sick atm, can't really find the strength to do a proper review. Looks good though on first glance though. I will be using this branch for a few days and submit a proper review and any bugs when I get better. 😷

**Comment by shadmansaleh** [comment]
Get well soon 😇

**Comment by hoob3rt** [comment]
I will probably have time to look at it on friday. Sorry it's taking so long 😞

**Comment by shadmansaleh** [comment]
The last commit I pushed stops lualine crash for invalid theme name . I know this should be a separate pr . It's a pretty trivial consider this pr the refactors I thought of doing 😉

> I will probably have time to look at it on friday. Sorry it's taking so long 😞

Not a problem . I've exam on friday that's why I'm quite busy this week . Are you well now ?

**Comment by hoob3rt** [comment]
>  I've exam on friday that's why I'm quite busy this week . 

Best of luck!

> Are you well now ?

Yeah, thanks :smile:

**Comment by hoob3rt** [comment]
I would personally split the var/function component to two separate ones. Or at least extract the logic to two functions in given class. Otherwise lgtm I think

**Comment by shadmansaleh** [comment]
Ok I can do that .

**Comment by shadmansaleh** [comment]
Done.

**Comment by shadmansaleh** [comment]
@hoob3rt can you run lua-format before merge on this pr . For some reason it's not getting installed properly in my system . It's [this](https://github.com/Koihik/LuaFormatter#readme) one right ?

**Comment by shadmansaleh** [comment]
> can you run lua-format before merge on this pr?

Won't be needed any more i've resolved the issue

**Comment by shadmansaleh** [comment]
@hoob3rt can you please give me a date on when you'll be free to review these ?

**Review by hoob3rt — APPROVED** [review]
I'm fine with these changes, lgtm

**Comment by shadmansaleh** [comment]
Then merge ?

**Comment by Shatur95** [comment]
After this PR the following configuration no longer works:

```lua
require('lualine').setup{
  sections = {
    lualine_x = {require('lsp-status').status}
  }
}
```

Where `require('lsp-status').status` is a lua function from [this](https://github.com/nvim-lua/lsp-status.nvim) plugin

**Comment by shadmansaleh** [comment]
@Shatur95 can you confirm #175 resolves the issue ?

**Pull request merged**
