### PR TITLE
Add modus_vivendi theme

### PR DESCRIPTION
**Pull request by ronniedroid**
adds a theme based on modus_vivendi https://protesilaos.com/modus-themes/

vim version of the theme can be though here: https://github.com/ishan9299/modus-theme-vim

modus_vivendinormal
modus_vivendiinsert
modus_vivendivisual
modus_vivendireplace

### CODE REVIEW

**Comment by hoob3rt** [comment]
needs lua-format & docstring comment, otherwise lgtm
```
-- Copyright (c) 2020-2021 ronniedroid
-- MIT license, see LICENSE for more details.
```

**Comment by ronniedroid** [comment]
Hello, I made the changes requested,  good to be merge I think.

**Comment by hoob3rt** [comment]
> Hello, I made the changes requested, good to be merge I think.

I agree, thanks :smile:

**Comment by allumik** [comment]
Any love for the light variant `modus-operandi` ?

**Pull request merged**
