### PR TITLE
Fix #33

### LINKED ISSUE #33: more universal way of setting the statusline
https://github.com/hoob3rt/lualine.nvim/blob/4cf4ac814d5c7acf6470f37047bf771d7cb67e55/lua/lualine.lua#L105-L115

There should be a better way of making lualine use different function calls for each window. This hack is ugly and will probably prove to be hard to maintain.

### PR DESCRIPTION
**Pull request by shadmansaleh**
A posible solution to #33

### CODE REVIEW

**Comment by hoob3rt** [comment]
That looks a lot cleaner for sure. I will use it on my workbench tomorrow and merge if I don't stumble across any bugs. Thanks :)

**Comment by hoob3rt** [comment]
lgtm

**Comment by megalithic** [comment]
@hoob3rt i THINK this might have reintroduced the issue with inactive buffers replicating the info in those components, e.g. filename being the same between active and inactive, etc.

**Comment by shadmansaleh** [comment]
>@hoob3rt i THINK this might have reintroduced the issue with inactive buffers replicating the info in those components, e.g. filename being the same between active and inactive, etc.

Yes you are right this intoduced it . I'm trying to fix the bug without reverting it . Though I cann't understand why it's happening . It seems accessing vim.bo gets the active buffer not the buffer the function was called for .

**Pull request merged**
