### PR TITLE
Add max_chars to filename

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
requires: https://github.com/hoob3rt/lualine.nvim/pull/197
(only because I'm using both features locally)

Preview (same config as the other PR): 
image

### CODE REVIEW

**Comment by hoob3rt** [comment]
There is no need for this to have #197 changes inside. Remove 05fda1f from this pr and we can merge this.

**Comment by NullVoxPopuli** [comment]
@hoob3rt commit dropped

**Comment by shadmansaleh** [comment]
I agree with thia change but max_char is probablya  bad name . It's not quite understandable what it does seeing that name . Also the deascription in docs is miss leading since pathshorten doesn't garantee length will be under max_char. Plus you didn't update the docs in `doc/lualine.txt`

**Comment by NullVoxPopuli** [comment]
maybe `shorten_at_length`?

**Comment by shadmansaleh** [comment]
> maybe shorten_at_length

Maybe . Better then max_chars imo .I'm not sure about the name . Maybe you can take input from @hoob3rt :)

**Comment by NullVoxPopuli** [comment]
less configuration! https://github.com/hoob3rt/lualine.nvim/pull/201

**Pull request closed without merging**
