### PR TITLE
create a new theme called shadoline

### PR DESCRIPTION
**Pull request by TarunDaCoder**

### CODE REVIEW

**Comment by hoob3rt** [comment]
needs screenshots, refer to [CONTRIBUTING.md](https://github.com/hoob3rt/lualine.nvim/blob/master/CONTRIBUTING.md)

**Comment by TarunDaCoder** [comment]
Ok 1 min

**Comment by TarunDaCoder** [comment]
Ok

**Comment by TarunDaCoder** [comment]
I have created a new pull request for this theme, I have also edited the theme a little bit.

**Pull request closed without merging**
