### PR TITLE
Made theme parameters positional

### PR DESCRIPTION
**Pull request by shadmansaleh**
Removed old fg, bg, gui named parameters

Now themes work provide a dictionary in this formate
`{ forground_color, backround_color, special_effect }`

I think this simplifies the themes.

### CODE REVIEW

**Comment by hoob3rt** [comment]
Yeah... I'm not a fan of this change at all. This has absolutely no benefit imo and only creates confusion. I think themes are really easy to write right now and anyone can do it, with this change only you and I will know what's going on.

**Comment by shadmansaleh** [comment]
>I think themes are really easy to write right now and anyone can do it, with this change only you and I will know what's going on.

I looked at airline and lightline themes they are using positional arguments That's why I thought taking positional argument will make it easier to port them to lualine. Also I think It's not hard to figure out seeing the examples.

**Comment by hoob3rt** [comment]
> > I think themes are really easy to write right now and anyone can do it, with this change only you and I will know what's going on.
> 
> I looked at airline and lightline themes they are using positional arguments That's why I thought taking positional argument will make it easier to port them to lualine. Also I think It's not hard to figure out seeing the examples.

There is no difference in porting lightline's themes to `master` or this change.

I stand by my argument, I think airline's and lightline's theme definitions are a mess. Look at lightline gruvbox implementation here.

```vim
if exists('g:lightline')

  let s:bg0  = s:getGruvColor('GruvboxBg0')
  let s:bg1  = s:getGruvColor('GruvboxBg1')
  let s:bg2  = s:getGruvColor('GruvboxBg2')
  let s:bg4  = s:getGruvColor('GruvboxBg4')
  let s:fg1  = s:getGruvColor('GruvboxFg1')
  let s:fg4  = s:getGruvColor('GruvboxFg4')

  let s:yellow = s:getGruvColor('GruvboxYellow')
  let s:blue   = s:getGruvColor('GruvboxBlue')
  let s:aqua   = s:getGruvColor('GruvboxAqua')
  let s:orange = s:getGruvColor('GruvboxOrange')
  let s:red = s:getGruvColor('GruvboxRed')
  let s:green = s:getGruvColor('GruvboxGreen')

  let s:p = {'normal':{}, 'inactive':{}, 'insert':{}, 'replace':{}, 'visual':{}, 'tabline':{}, 'terminal':{}}
  let s:p.normal.left = [ [ s:bg0, s:fg4, 'bold' ], [ s:fg4, s:bg2 ] ]
  let s:p.normal.right = [ [ s:bg0, s:fg4 ], [ s:fg4, s:bg2 ] ]
  let s:p.normal.middle = [ [ s:fg4, s:bg1 ] ]
  let s:p.inactive.right = [ [ s:bg4, s:bg1 ], [ s:bg4, s:bg1 ] ]
  let s:p.inactive.left =  [ [ s:bg4, s:bg1 ], [ s:bg4, s:bg1 ] ]
  let s:p.inactive.middle = [ [ s:bg4, s:bg1 ] ]
  let s:p.insert.left = [ [ s:bg0, s:blue, 'bold' ], [ s:fg1, s:bg2 ] ]
  let s:p.insert.right = [ [ s:bg0, s:blue ], [ s:fg1, s:bg2 ] ]
  let s:p.insert.middle = [ [ s:fg4, s:bg1 ] ]
  let s:p.terminal.left = [ [ s:bg0, s:green, 'bold' ], [ s:fg1, s:bg2 ] ]
  let s:p.terminal.right = [ [ s:bg0, s:green ], [ s:fg1, s:bg2 ] ]
  let s:p.terminal.middle = [ [ s:fg4, s:bg1 ] ]
  let s:p.replace.left = [ [ s:bg0, s:aqua, 'bold' ], [ s:fg1, s:bg2 ] ]
  let s:p.replace.right = [ [ s:bg0, s:aqua ], [ s:fg1, s:bg2 ] ]
  let s:p.replace.middle = [ [ s:fg4, s:bg1 ] ]
  let s:p.visual.left = [ [ s:bg0, s:orange, 'bold' ], [ s:bg0, s:bg4 ] ]
  let s:p.visual.right = [ [ s:bg0, s:orange ], [ s:bg0, s:bg4 ] ]
  let s:p.visual.middle = [ [ s:fg4, s:bg1 ] ]
  let s:p.tabline.left = [ [ s:fg4, s:bg2 ] ]
  let s:p.tabline.tabsel = [ [ s:bg0, s:fg4 ] ]
  let s:p.tabline.middle = [ [ s:bg0, s:bg4 ] ]
  let s:p.tabline.right = [ [ s:bg0, s:orange ] ]
  let s:p.normal.error = [ [ s:bg0, s:red ] ]
  let s:p.normal.warning = [ [ s:bg0, s:yellow ] ]

  let g:lightline#colorscheme#gruvbox#palette = lightline#colorscheme#flatten(s:p)
endif
```

I have no idea what's going on here at first glance

**Comment by shadmansaleh** [comment]
Alright then .

**Pull request closed without merging**
