### PR TITLE
Asymatric themeing

### PR DESCRIPTION
**Pull request by shadmansaleh**
Continuing #28
Allows `x,y,z` to be indivisualy themed.

### CODE REVIEW

**Comment by hoob3rt** [comment]
Why did you close this pr?

**Comment by shadmansaleh** [comment]
While working on #55 I've realized this wonn't work .
If we are to create asymatric themes we will have to keep  a middle part that is always present . So this cann't work .

Even curently the statusline depends on user keeping every component active . Try commenting out `c` in your config or all `x,y,z` or `a,b,c` you will find some amazing results. best one is only have `a` available . The whole statusline takes up a . I've tried to deal with it on #55 .

**Comment by hoob3rt** [comment]
I understand what the issue is, I have not thought of it before. Please open a new issue with this. 

I think we should try to tackle it in a new pr BEFORE we do #55. Also, #55 should handle only what it states, I had no idea it fixes any theming issues right now :)

**Comment by shadmansaleh** [comment]
>I think we should try to tackle it in a new pr BEFORE we do #55. Also, #55 should handle only what it states, I had no idea it fixes any theming issues right now :)
 
I basicaly had to rewrite most of statusline function for implementing #55 as it required new highlights for each separator . As I've changed the interpretation of themes there to make looks more consistent . (Simply I've made so `c` sections highlighting is always present. An `a,b,c` compartment always render on leftaligned and `x,y,z` rightaligned )

I think if we want to change themeing we can do that on top of #55 .

**Comment by shadmansaleh** [comment]
Those bugs are mainly there because of curent implementation of statusline function doesn't account for execption . Specialy on section_c it '%=' if c is skiped it's not added . Even if those bugs are fixed in this implementation . After #55 merges they will be replaced by new implementation of statusline function.
So I think fixing them here is unnessery.

**Comment by hoob3rt** [comment]
Yeah sure. I will take a look at #55 asap and hopefully we will get it fixed :)

**Pull request closed without merging**
