### PR TITLE
Add Horizon theme

### PR DESCRIPTION
**Pull request by Jnhtr**
Based off the Horizon VS-Code  theme.

### CODE REVIEW

**Comment by hoob3rt** [comment]
This is great, just need a few things:
* add a copyright comment with your username at the top of a file
* disable luaformatter for the color table
* change `Horizon` to be lowercase in `THEMES.md` (since the filename is `horizon`)

The first two points is basically a copy paste from any other theme in the codebase.

**Comment by Jnhtr** [comment]
> This is great, just need a few things:
> 
> * add a copyright comment with your username at the top of a file
> * disable luaformatter for the color table
> * change `Horizon` to be lowercase in `THEMES.md` (since the filename is `horizon`)
> 
> The first two points is basically a copy paste from any other theme in the codebase.

First timer, apologies! I've corrected these now.

**Comment by hoob3rt** [comment]
Looks good, thank you 😄

**Comment by Jnhtr** [comment]
> Looks good, thank you 😄 

Thank you for your patience with my errors! 😊

**Pull request merged**
