### PR TITLE
Porting onedark theme

### PR DESCRIPTION
**Pull request by teddylear**
Please let me know if there is anything else that needs to be done here. Used [onedark's airline theme in it's repo](https://github.com/joshdick/onedark.vim/blob/master/autoload/airline/themes/onedark.vim) as reference.

### CODE REVIEW

**Comment by hoob3rt** [comment]
pic-window-210102-1652-18
Are you sure you have not mistaken `fg` with `bg`? This looks weird...

**Comment by hoob3rt** [comment]
Also you have not set `M.command` as said in https://github.com/hoob3rt/lualine.nvim/issues/9

Please set it to something, `lualine`'s highlight should fall back to `lualine_normal` but it is currently not supported. Even
```lua
M.command = M.normal
```
will do fine as long as the highlights make sense with ported colorscheme.

**Comment by teddylear** [comment]
@hoob3rt Thanks for the review! I addressed both comments with another commit, please let me know if there is anything else I should address.

**Comment by hoob3rt** [comment]
@teddylear looks good now. Please add onedark to `README.md` and it should be ready to merge.

**Comment by teddylear** [comment]
@hoob3rt Added theme to list on README.

**Pull request merged**
